sudo: false
language: java

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - BUILD_COMMIT=b${TRAVIS_BUILD_NUMBER}_g${COMMIT}

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches
  - $HOME/.gradle/native
  - $HOME/.gradle/wrapper

before_install:
- echo "[INFO] BUILD_COMMIT> $BUILD_COMMIT"
- sed -i -e "/version/s/-/-$BUILD_COMMIT-/g" gradle.properties

script: ./gradlew check shadowJar

after_success:
- ls -lR build/

matrix:
  include:
  - jdk: oraclejdk8
  - jdk: oraclejdk9
  - jdk: openjdk8
  - jdk: openjdk9
    if: tag IS blank

deploy:
  provider: releases
  api_key:
    secure: iKXXqoxPMsoLGlhKMwRB7dVdU0ZvOjzRaxm73zjEsEgyErL7LJ6YG+3wJl24UW8zxgpvM5hW0DKUkWSLfVoHa/1l+Bsb8yREAKJTYldZs3pjhQxWM7OBMeKWjTA7WccYrx4ShHgbgUvl4IuHXNY91kcu1pC6lZukpDUvdX4Ii70=
  file_glob: true
  file: "build/libs/ksar-*all.jar"
  skip_cleanup: true
  on:
    tags: true
    repo: vlsi/ksar
